# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'PeopleMon' do
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SwiftKeychainWrapper'
pod 'MBProgressHUD'
pod 'SnapKit'
pod 'AFDateHelper'
pod 'JSQMessagesViewController'
end
